{application,genProto,
             [{description,"An OTP library"},
              {vsn,"0.1.0"},
              {registered,[]},
              {applications,[kernel,stdlib]},
              {env,[]},
              {modules,[protoCode,protoCode_bak,protoField,protoGen,
                        protoParse]},
              {licenses,["Apache 2.0"]},
              {links,[]}]}.
